### PR TITLE
Remove now-cd from dev deps

### PR DESCRIPTION
**Pull request by siddharthkp**

### CODE REVIEW

**Comment by siddharthkp** [comment]
401 Access denied.

1. Make sure you have added the required API tokens to travis settings: https://github.com/siddharthkp/now-cd#install

2. Can you create an issue to remind me to handle infinite retries 🙈

**Comment by Kikobeats** [comment]
Hmmm apparently the problem right know is that the project is not public, even I'm passing `--public` flag

```
$ npx now-cd --public --alias "master=changes.now.sh"
 NOW CD  Deployment started 
unhandledRejection { Error: Command failed: /bin/sh -c /home/travis/.npm/_npx/3183/lib/node_modules/now-cd/node_modules/.bin/now -t [secure]  -e NODE_ENV=production
> Error! Unexpected error. Please try again later. (
You are on the OSS plan. Your code and logs will be made public. If you agree with that, please run again with --public.)
```

https://travis-ci.org/Kikobeats/changelog.now.sh/jobs/366467647#L3399

**Comment by Kikobeats** [comment]
I think `now-cd` not support `---public` yet 🤔

**Comment by siddharthkp** [comment]
Oh yeah, it doesn't!

If you'd like this is the right place to add it: https://github.com/siddharthkp/now-cd/blob/master/command.js

**Pull request merged**
